### ISSUE TITLE
Issue with Patcher's container backgrounds feature

### ISSUE THREAD

**Issue by gepbird** [symt/BazaarNotifier#37]
There's a feature in Patcher that removes backgrounds from GUIs, other mods usually don't get affected by this, their background stays the same. But BazaarNotifier has a white background while this feature is on. You could make it so it still has the gray background.

**Comment by symt** [comment]
This is a known issue. Currently, I'm not properly rendering the background. It's gray because it is rendered behind the that background that's removed by patcher. I'm working on a way around this.

I'm no expert on forge's rendering cycles so this is going to take a bit of research. If anyone has other examples of squares of various colors being rendered while a ChestGUI is open, please let me know. Once this is fixed, I can finally add the ability to change the color of the gui.

**Comment by PentBeear** [comment]
> This is a known issue. Currently, I'm not properly rendering the background. It's gray because it is rendered behind the that background that's removed by patcher. I'm working on a way around this.
> 
> I'm no expert on forge's rendering cycles so this is going to take a bit of research. If anyone has other examples of squares of various colors being rendered while a ChestGUI is open, please let me know. Once this is fixed, I can finally add the ability to change the color of the gui.

My god awful mod somewhat did this, [https://github.com/PentBeear/BazcalMod/tree/master/src/main/java/com/bazcal/gui](url). Yes it is a bazaar mod, it was awful, but you might be able to get something out of it when it comes to rendering backgrounds.

**Comment by symt** [comment]
This should be fixed in a later version. I'm rendering slightly differently (the same way it's done for the puzzle solvers). The code is complete, just needs a bit more testing

**Comment by symt** [comment]
#38 fixed
